### ISSUE TITLE
Unable to publish module

### ISSUE THREAD

**Issue by andrewliebchen** [kysely/framer-modules#1]
Love this app and was really excited to give it a try. Unfortunately, it's not working. 

I've attached an image of the error alert. Please check my code [here](https://github.com/andrewliebchen/FramerLoremIpsum) to see if I'm doing anything wrong!

<img width="466" alt="screenshot 2017-08-28 16 40 28" src="https://user-images.githubusercontent.com/1839748/29798189-6b3958b4-8c10-11e7-9149-4b335f8cc1f8.png">

**Comment by kysely** [comment]
Hi Andrew,
I'm sorry to tell you the error actually lies within your `module.json` file. There's a **trailing comma** (after `example` key) which is not allowed in JSON format.

However, thanks for pointing out this issue. I've just implemented more robust JSON parsing on [the server](https://github.com/kysely/framer-modules-server) so that users are getting nicer and more informative errors as this is easy-to-make mistake :smile:

**Comment by andrewliebchen** [comment]
Awesome, I was hoping it was an error on my side I wasn't able to see.
Thanks for checking it out!
